steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'demo-backend'  # 👈 das ist wichtig!
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/quarkus-app',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/quarkus-app'
