steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile',                    # Dockerfile liegt direkt in demo-backend
      '-t', 'gcr.io/$PROJECT_ID/quarkus-app',
      '.'                                    # Kontext: alles in demo-backend
    ]
    dir: 'demo-backend'  # <- DAS ist der Fix: wir betreten /demo-backend vor dem Build
images:
  - 'gcr.io/$PROJECT_ID/quarkus-app'
