steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/quarkus-app',
      '.'  # 👈 Build-Kontext ist Root des Repos
    ]
    dir: '.'  # 👈 wichtig: das ist der Ordner mit Dockerfile & pom.xml
images:
  - 'gcr.io/$PROJECT_ID/quarkus-app'
