steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'demo-backend/Dockerfile',        # 👈 Pfad zur Dockerfile im Repo
      '-t', 'gcr.io/$PROJECT_ID/quarkus-app', # 👈 Image-Tag
      '.'                                      # 👈 Kontext wird unten gesetzt
    ]
    dir: 'demo-backend'  # 👈 DAS MACHT DEN UNTERSCHIED!
images:
  - 'gcr.io/$PROJECT_ID/quarkus-app'
