steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'demo-backend/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/quarkus-app',
      'demo-backend'  # 👈 das ist jetzt der Kontext
    ]
images:
  - 'gcr.io/$PROJECT_ID/quarkus-app'
