steps:
  - name: 'alpine'
    entrypoint: sh
    args: ['-c', 'echo "🕵️ Check files im Kontext:" && ls -la && echo "---" && ls -la demo-backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/quarkus-app',
      '.'
    ]
    dir: 'demo-backend'

images:
  - 'gcr.io/$PROJECT_ID/quarkus-app'
